nuetral_cards = [
  {name: 'Abomination', card_type: 'Minion', hero: 'Nuetral', cost: 5, attack: 4, defense: 4, description: 'Taunt. Deathrattle: Deal 2 damage to ALL characters.'},
  {name: 'Abusive Sergeant', card_type: 'Minion', hero: 'Nuetral', cost: 1, attack: 2, defense: 1, description: 'Battlecry: Give a minion +2 Attack this turn.'},
  {name: 'Acidic Swamp Ooze', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 3, defense: 2, description: "Battlecry: Destroy your opponent's weapon."},
  {name: 'Acolyte of Pain', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 1, defense: 3, description: 'Whenever this minion takes damage, draw a card.'},
  {name: 'Alarm-o-Bot', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 0, defense: 3, description: 'At the start of your turn, swap this minion with a random one in your hand.'},
  {name: 'Alexstrasza', card_type: 'Minion', hero: 'Nuetral', cost: 9, attack: 8, defense: 8, description: "Battlecry: Set a hero's remaining Health to 15."},
  {name: 'Amani Berserker', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 2, defense: 3, description: 'Enrage: +3 Attack'},
  {name: 'Ancient Brewmaster', card_type: 'Minion', hero: 'Nuetral', cost: 4, attack: 5, defense: 4, description: 'Battlecry: Return a friendly minion from the battlefield to your hand.'},
  {name: 'Ancient Mage', card_type: 'Minion', hero: 'Nuetral', cost: 4, attack: 2, defense: 5, description: 'Battlecry: Give adjacent minions Spell Damage +1.'},
  {name: 'Ancient Watcher', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 4, defense: 5, description: "Can't Attack."},
  {name: 'Angry Chicken', card_type: 'Minion', hero: 'Nuetral', cost: 1, attack: 1, defense: 1, description: 'Enrage: +5 Attack.'},
  {name: 'Arcane Golem', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 4, defense: 2, description: 'Charge. Battlecry: Give your opponent a Mana Crystal.'},
  {name: 'Archmage', card_type: 'Minion', hero: 'Nuetral', cost: 6, attack: 4, defense: 7, description: 'Spell Damage +1'},
  {name: 'Argent Commander', card_type: 'Minion', hero: 'Nuetral', cost: 6, attack: 4, defense: 2, description: 'Spell Damage +1'},
  {name: 'Argent Squire', card_type: 'Minion', hero: 'Nuetral', cost: 1, attack: 1, defense: 1, description: 'Divine Shield'},
  {name: 'Azure Drake', card_type: 'Minion', hero: 'Nuetral', cost: 5, attack: 4, defense: 4, description: 'Spell Damage +1. Battlecry: Draw a card.'},
  {name: 'Baron Geddon', card_type: 'Minion', hero: 'Nuetral', cost: 7, attack: 7, defense: 5, description: 'Battlecry: Destroy a minion with an Attack of 7 or more.'},
  {name: 'Big Game Hunter', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 4, defense: 2, description: 'Battlecry: Destroy a minion with an Attack of 7 or more.'},
  {name: 'Blood Knight', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 3, defense: 3, description: 'Battlecry: All minions lose Divine Shield. Gain +3/+3 for each Shield lost.'},
  {name: 'Bloodfen Raptor', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 3, defense: 2, description: ''},
  {name: 'Bloodmage Thalnos', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 1, defense: 1, description: 'Spell Damage +1. Deathrattle: Draw a card.'},
  {name: 'Bloodsail Corsair', card_type: 'Minion', hero: 'Nuetral', cost: 1, attack: 1, defense: 2, description: "Battlecry: Remove 1 Durability from your opponent's weapon."},
  {name: 'Bloodsail Raider', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 2, defense: 3, description: 'Battlecry: Gain Attack equal to the Attack of your weapon.'},
  {name: 'Bluegill Warrior', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 2, defense: 1, description: 'Charge'},
  {name: 'Booty Bay Bodyguard', card_type: 'Minion', hero: 'Nuetral', cost: 5, attack: 5, defense: 4, description: 'Taunt'},
  {name: 'Boulderfist Ogre', card_type: 'Minion', hero: 'Nuetral', cost: 6, attack: 6, defense: 7, description: ''},
  {name: 'Cairne Bloodhoof', card_type: 'Minion', hero: 'Nuetral', cost: 6, attack: 4, defense: 5, description: 'Deathrattle: Summon a 4/5 Baine Bloodhoof.'},
  {name: 'Captain Greenskin', card_type: 'Minion', hero: 'Nuetral', cost: 5, attack: 5, defense: 4, description: 'Battlecry: Give your weapon +1/+1.'},
  {name: "Captain's Parrot", card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 1, defense: 1, description: 'Battlecry: Put a random Pirate from your deck into your hand.'},
  {name: 'Chillwind Yeti', card_type: 'Minion', hero: 'Nuetral', cost: 4, attack: 4, defense: 5, description: ''},
  {name: 'Coldlight Oracle', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 2, defense: 2, description: 'Battlecry: Each player draws 2 cards.'},
  {name: 'Coldlight Seer', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 2, defense: 3, description: 'Battlecry: Give ALL other Murlocs +2 Health.'},
  {name: 'Core Hound', card_type: 'Minion', hero: 'Nuetral', cost: 7, attack: 9, defense: 5, description: ''},
  {name: 'Crazed Alchemist', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 2, defense: 2, description: 'Battlecry: Swap the Attack and Health of a minion.'},
  {name: 'Cult Master', card_type: 'Minion', hero: 'Nuetral', cost: 4, attack: 4, defense: 2, description: 'Whenever one of your other minions dies, draw a card.'},
  {name: 'Dalaran Mage', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 1, defense: 4, description: 'Spell Damage +1'},
  {name: 'Dark Iron Dwarf', card_type: 'Minion', hero: 'Nuetral', cost: 4, attack: 4, defense: 4, description: 'Battlecry: Give a minion +2 Attack this turn.'},
  {name: 'Darkscale Healer', card_type: 'Minion', hero: 'Nuetral', cost: 5, attack: 4, defense: 5, description: 'Battlecry: Restore 2 Health to all friendly characters.'},
  {name: 'Deathwing', card_type: 'Minion', hero: 'Nuetral', cost: 10, attack: 12, defense: 12, description: 'Battlecry: Destroy all other minions and discard your hand.'},
  {name: 'Defender of Argus', card_type: 'Minion', hero: 'Nuetral', cost: 4, attack: 2, defense: 3, description: 'Battlecry: Give adjacent minions +1/+1 and Taunt.'},
  {name: 'Demolisher', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 1, defense: 4, description: 'At the start of your turn, deal 2 damage to a random enemy.'},
  {name: 'Dire Wolf Alpha', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 2, defense: 2, description: 'Adjacent minions have +1 Attack.'},
  {name: 'Doomsayer', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 0, defense: 7, description: 'At the start of your turn, destroy ALL minions.'},
  {name: 'Dragonling Mechanic', card_type: 'Minion', hero: 'Nuetral', cost: 4, attack: 2, defense: 4, description: 'Battlecry: Summon a 2/1 Mechanical Dragonling.'},
  {name: 'Dread Corsair', card_type: 'Minion', hero: 'Nuetral', cost: 4, attack: 3, defense: 3, description: 'Taunt. Costs (1) less per Attack of your weapon.'},
  {name: 'Earthen Ring Farseer', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 3, defense: 3, description: 'Battlecry: Restore 3 Health.'},
  {name: 'Elite Tauren Chieftain', card_type: 'Minion', hero: 'Nuetral', cost: 5, attack: 5, defense: 5, description: 'Battlecry: Give both players the power to ROCK! (with a Power Chord card)'},
  {name: 'Elven Archer', card_type: 'Minion', hero: 'Nuetral', cost: 1, attack: 1, defense: 1, description: 'Battlecry: Deal 1 damage.'},
  {name: 'Emperor Cobra', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 2, defense: 3, description: 'Destroy any minion damaged by this minion.'},
  {name: 'Faceless Manipulator', card_type: 'Minion', hero: 'Nuetral', cost: 5, attack: 3, defense: 3, description: 'Battlecry: Choose a minion and become a copy of it.'},
  {name: 'Faerie Dragon', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 3, defense: 2, description: 'Battlecry: Choose a minion and become a copy of it.'},
  {name: 'Fen Creeper', card_type: 'Minion', hero: 'Nuetral', cost: 5, attack: 3, defense: 6, description: 'Battlecry: Choose a minion and become a copy of it.'},
  {name: 'Flesheating Ghoul', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 2, defense: 3, description: 'Whenever a minion dies, gain +1 Attack.'},
  {name: 'Frost Elemental', card_type: 'Minion', hero: 'Nuetral', cost: 6, attack: 5, defense: 5, description: 'Battlecry: Freeze a character.'},
  {name: 'Frostwolf Grunt', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 2, defense: 2, description: 'Taunt'},
  {name: 'Frostwolf Warlord', card_type: 'Minion', hero: 'Nuetral', cost: 5, attack: 4, defense: 4, description: 'Battlecry: Gain +1/+1 for each other friendly minion on the battlefield.'},
  {name: 'Gadgetzan Auctioneer', card_type: 'Minion', hero: 'Nuetral', cost: 5, attack: 4, defense: 4, description: 'Whenever you cast a spell, draw a card.'},
  {name: 'Gelbin Mekkatorque', card_type: 'Minion', hero: 'Nuetral', cost: 6, attack: 6, defense: 6, description: 'Battlecry: Summon an AWESOME invention.'},
  {name: 'Gnomish Inventor', card_type: 'Minion', hero: 'Nuetral', cost: 4, attack: 2, defense: 4, description: 'Battlecry: Draw a card.'},
  {name: 'Goldshire Footman', card_type: 'Minion', hero: 'Nuetral', cost: 1, attack: 1, defense: 2, description: 'Taunt'},
  {name: 'Grimscale Oracle', card_type: 'Minion', hero: 'Nuetral', cost: 1, attack: 1, defense: 1, description: 'ALL other Murlocs have +1 Attack.'},
  {name: 'Gruul', card_type: 'Minion', hero: 'Nuetral', cost: 8, attack: 7, defense: 7, description: 'At the end of each turn, gain +1/+1 .'},
  {name: 'Gurubashi Berserker', card_type: 'Minion', hero: 'Nuetral', cost: 5, attack: 2, defense: 7, description: 'Whenever this minion takes damage, gain +3 Attack.'},
  {name: 'Harrison Jones', card_type: 'Minion', hero: 'Nuetral', cost: 5, attack: 5, defense: 4, description: "Battlecry: Destroy your opponent's weapon and draw cards equal to its Durability."},
  {name: 'Harvest Golem', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 2, defense: 3, description: 'Deathrattle: Summon a 2/1 Damaged Golem.'},
  {name: 'Hogger', card_type: 'Minion', hero: 'Nuetral', cost: 6, attack: 4, defense: 4, description: 'At the end of your turn, summon a 2/2 Gnoll with Taunt.'},
  {name: 'Hungry Crab', card_type: 'Minion', hero: 'Nuetral', cost: 1, attack: 1, defense: 2, description: 'Battlecry: Destroy a Murloc and gain +2/+2.'},
  {name: 'Illidan Stormrage', card_type: 'Minion', hero: 'Nuetral', cost: 6, attack: 7, defense: 5, description: 'Whenever you play a card, summon a 2/1 Flame of Azzinoth.'},
  {name: 'Imp Master', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 1, defense: 5, description: 'At the end of your turn, deal 1 damage to this minion and summon a 1/1 Imp.'},
  {name: 'Injured Blademaster', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 4, defense: 7, description: 'Battlecry: Deal 4 damage to HIMSELF.'},
  {name: 'Ironbeak Owl', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 2, defense: 1, description: 'Battlecry: Silence a minion.'},
  {name: 'Ironforge Rifleman', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 2, defense: 2, description: 'Battlecry: Deal 1 damage.'},
  {name: 'Ironfur Grizzly', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 3, defense: 3, description: 'Taunt'},
  {name: 'Jungle Panther', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 4, defense: 2, description: 'Stealth'},
  {name: 'King Mukla', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 5, defense: 5, description: 'Battlecry: Give your opponent 2 Bananas.'},
  {name: 'Knife Juggler', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 3, defense: 2, description: 'After you summon a minion, deal 1 damage to a random enemy.'},
  {name: 'Kobold Geomancer', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 2, defense: 2, description: 'Spell Damage +1'},
  {name: 'Leeroy Jenkins', card_type: 'Minion', hero: 'Nuetral', cost: 4, attack: 6, defense: 2, description: 'Charge. Battlecry: Summon two 1/1 Whelps for your opponent.'},
  {name: 'Leper Gnome', card_type: 'Minion', hero: 'Nuetral', cost: 1, attack: 2, defense: 1, description: 'Deathrattle: Deal 2 damage to the enemy hero.'},
  {name: 'Lightwarden', card_type: 'Minion', hero: 'Nuetral', cost: 1, attack: 1, defense: 2, description: 'Whenever a character is healed, gain +2 Attack.'},
  {name: 'Loot Hoarder', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 2, defense: 1, description: 'Deathrattle: Draw a card.'},
  {name: 'Lord of the Arena', card_type: 'Minion', hero: 'Nuetral', cost: 6, attack: 6, defense: 5, description: 'Taunt'},
  {name: 'Lorewalker Cho', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 0, defense: 4, description: 'Whenever a player casts a spell, put a copy into the other player’s hand.'},
  {name: 'Mad Bomber', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 3, defense: 2, description: 'Battlecry: Deal 3 damage randomly split between all other characters.'},
  {name: 'Magma Rager', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 5, defense: 1, description: ''},
  {name: 'Malygos', card_type: 'Minion', hero: 'Nuetral', cost: 9, attack: 4, defense: 12, description: 'Spell Damage +5'},
  {name: 'Mana Addict', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 1, defense: 3, description: 'Whenever you cast a spell, gain +2 Attack this turn.'},
  {name: 'Mana Wraith', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 2, defense: 2, description: 'ALL minions cost (1) more.'},
  {name: 'Master Swordsmith', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 1, defense: 3, description: 'At the end of your turn, give another random friendly minion +1 Attack.'},
  {name: 'Millhouse Manastorm', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 4, defense: 4, description: 'Battlecry: Enemy spells cost (0) next turn.'},
  {name: 'Mind Control Tech', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 3, defense: 3, description: 'Battlecry: If your opponent has 4 or more minions, take control of one at random.'},
  {name: "Mogu'shan Warden", card_type: 'Minion', hero: 'Nuetral', cost: 4, attack: 1, defense: 7, description: 'Taunt'},
  {name: 'Molten Giant', card_type: 'Minion', hero: 'Nuetral', cost: 20, attack: 8, defense: 8, description: 'Costs (1) less for each damage your hero has taken.'},
  {name: 'Mountain Giant', card_type: 'Minion', hero: 'Nuetral', cost: 12, attack: 8, defense: 8, description: 'Costs (1) less for each other card in your hand.'},
  {name: 'Murloc Raider', card_type: 'Minion', hero: 'Nuetral', cost: 1, attack: 2, defense: 1, description: ''},
  {name: 'Murloc Tidecaller', card_type: 'Minion', hero: 'Nuetral', cost: 1, attack: 1, defense: 2, description: 'Whenever a Murloc is summoned, gain +1 Attack.'},
  {name: 'Murloc Tidehunter', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 2, defense: 1, description: 'Battlecry: Summon a 1/1 Murloc Scout.'},
  {name: 'Murloc Warleader', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 3, defense: 3, description: 'ALL other Murlocs have +2/+1.'},
  {name: 'Nat Pagle', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 0, defense: 4, description: 'At the end of your turn, you have a 50% chance to draw a card.'},
  {name: 'Nightblade', card_type: 'Minion', hero: 'Nuetral', cost: 5, attack: 4, defense: 4, description: 'Battlecry: Deal 3 damage to the enemy hero.'},
  {name: 'Novice Engineer', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 1, defense: 1, description: 'Battlecry: Draw a card.'},
  {name: 'Nozdormu', card_type: 'Minion', hero: 'Nuetral', cost: 9, attack: 8, defense: 8, description: 'Players only have 15 seconds to take their turns.'},
  {name: 'Oasis Snapjaw', card_type: 'Minion', hero: 'Nuetral', cost: 4, attack: 2, defense: 7, description: ''},
  {name: 'Ogre Magi', card_type: 'Minion', hero: 'Nuetral', cost: 4, attack: 4, defense: 4, description: 'Spell Damage +1'},
  {name: 'Old Murk-Eye', card_type: 'Minion', hero: 'Nuetral', cost: 4, attack: 2, defense: 4, description: 'Charge. Has +1 Attack for each other Murloc on the battlefield.'},
  {name: 'Onyxia', card_type: 'Minion', hero: 'Nuetral', cost: 9, attack: 8, defense: 8, description: 'Battlecry: Summon 1/1 Whelps until your side of the battlefield is full.'},
  {name: 'Pint-Sized Summoner', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 2, defense: 2, description: 'The first minion you play each turn costs (1) less.'},
  {name: 'Priestess of Elune', card_type: 'Minion', hero: 'Nuetral', cost: 6, attack: 5, defense: 4, description: 'Battlecry: Restore 4 Health to your hero.'},
  {name: 'Questing Adventurer', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 2, defense: 2, description: 'Whenever you play a card, gain +1/+1.'},
  {name: 'Raging Worgen', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 3, defense: 3, description: 'Enrage: Windfury and +1 Attack'},
  {name: 'Ragnaros the Firelord', card_type: 'Minion', hero: 'Nuetral', cost: 8, attack: 8, defense: 8, description: "Can't Attack. At the end of your turn, deal 8 damage to a random enemy."},
  {name: 'Raid Leader', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 2, defense: 2, description: 'Your other minions have +1 Attack.'},
  {name: 'Ravenholdt Assassin', card_type: 'Minion', hero: 'Nuetral', cost: 7, attack: 7, defense: 5, description: 'Stealth'},
  {name: 'Razorfen Hunter', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 2, defense: 3, description: 'Battlecry: Summon a 1/1 Boar.'},
  {name: 'Reckless Rocketeer', card_type: 'Minion', hero: 'Nuetral', cost: 6, attack: 5, defense: 2, description: 'Charge'},
  {name: 'River Crocolisk', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 2, defense: 3, description: ''},
  {name: 'Scarlet Crusader', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 3, defense: 1, description: 'Divine Shield'},
  {name: 'Sea Giant', card_type: 'Minion', hero: 'Nuetral', cost: 10, attack: 8, defense: 8, description: 'Costs (1) less for each other minion on the battlefield.'},
  {name: 'Secretkeeper', card_type: 'Minion', hero: 'Nuetral', cost: 1, attack: 1, defense: 2, description: 'Whenever a Secret is played, gain +1/+1.'},
  {name: "Sen'jin Shieldmasta", card_type: 'Minion', hero: 'Nuetral', cost: 4, attack: 3, defense: 5, description: 'Taunt'},
  {name: 'Shattered Sun Cleric', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 3, defense: 2, description: 'Battlecry: Give a friendly minion +1/+1.'},
  {name: 'Shieldbearer', card_type: 'Minion', hero: 'Nuetral', cost: 1, attack: 0, defense: 4, description: 'Taunt'},
  {name: 'Silver Hand Knight', card_type: 'Minion', hero: 'Nuetral', cost: 5, attack: 4, defense: 4, description: 'Battlecry: Summon a 2/2 Squire.'},
  {name: 'Silverback Patriarch', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 1, defense: 4, description: 'Taunt'},
  {name: 'Silvermoon Guardian', card_type: 'Minion', hero: 'Nuetral', cost: 4, attack: 3, defense: 3, description: 'Divine Shield'},
  {name: 'Southsea Captain', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 3, defense: 3, description: 'Your other Pirates have +1/+1.'},
  {name: 'Southsea Deckhand', card_type: 'Minion', hero: 'Nuetral', cost: 1, attack: 2, defense: 1, description: 'Has Charge while you have a weapon equipped.'},
  {name: 'Spellbreaker', card_type: 'Minion', hero: 'Nuetral', cost: 4, attack: 4, defense: 3, description: 'Battlecry: Silence a minion.'},
  {name: 'Spiteful Smith', card_type: 'Minion', hero: 'Nuetral', cost: 5, attack: 4, defense: 6, description: 'Enrage: Your weapon has +2 Attack.'},
  {name: 'Stampeding Kodo', card_type: 'Minion', hero: 'Nuetral', cost: 5, attack: 3, defense: 5, description: 'Battlecry: Destroy a random enemy minion with 2 or less Attack.'},
  {name: 'Stonetusk Boar', card_type: 'Minion', hero: 'Nuetral', cost: 1, attack: 1, defense: 1, description: 'Charge'},
  {name: 'Stormpike Commando', card_type: 'Minion', hero: 'Nuetral', cost: 5, attack: 4, defense: 2, description: 'Battlecry: Deal 2 damage.'},
  {name: 'Stormwind Champion', card_type: 'Minion', hero: 'Nuetral', cost: 7, attack: 6, defense: 6, description: 'Your other minions have +1/+1.'},
  {name: 'Stormwind Knight', card_type: 'Minion', hero: 'Nuetral', cost: 4, attack: 2, defense: 5, description: 'Charge'},
  {name: 'Stranglethorn Tiger', card_type: 'Minion', hero: 'Nuetral', cost: 5, attack: 5, defense: 5, description: 'Stealth'},
  {name: 'Sunfury Protector', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 2, defense: 3, description: 'Battlecry: Give adjacent minions Taunt.'},
  {name: 'Sunwalker', card_type: 'Minion', hero: 'Nuetral', cost: 6, attack: 4, defense: 5, description: 'Taunt. Divine Shield'},
  {name: 'Sylvanas Windrunner', card_type: 'Minion', hero: 'Nuetral', cost: 6, attack: 5, defense: 5, description: 'Deathrattle: Take control of a random enemy minion.'},
  {name: 'Tauren Warrior', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 2, defense: 3, description: 'Taunt. Enrage: +3 Attack'},
  {name: 'The Beast', card_type: 'Minion', hero: 'Nuetral', cost: 6, attack: 9, defense: 7, description: 'Deathrattle: Summon a 3/3 Finkle Einhorn for your opponent.'},
  {name: 'The Black Knight', card_type: 'Minion', hero: 'Nuetral', cost: 6, attack: 4, defense: 5, description: 'Battlecry: Destroy an enemy minion with Taunt.'},
  {name: 'Thrallmar Farseer', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 2, defense: 3, description: 'Windfury'},
  {name: 'Tinkmaster Overspark', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 2, defense: 2, description: 'Battlecry: Transform a minion into a 5/5 Devilsaur or a 1/1 Squirrel at random.'},
  {name: 'Twilight Drake', card_type: 'Minion', hero: 'Nuetral', cost: 4, attack: 4, defense: 1, description: 'Battlecry: Gain +1 Health for each card in your hand.'},
  {name: 'Venture Co. Mercenary', card_type: 'Minion', hero: 'Nuetral', cost: 5, attack: 7, defense: 6, description: 'Your minions cost (3) more.'},
  {name: 'Violet Teacher', card_type: 'Minion', hero: 'Nuetral', cost: 4, attack: 3, defense: 5, description: 'Whenever you cast a spell, summon a 1/1 Violet Apprentice.'},
  {name: 'Voodoo Doctor', card_type: 'Minion', hero: 'Nuetral', cost: 1, attack: 2, defense: 1, description: 'Battlecry: Restore 2 Health.'},
  {name: 'War Golem', card_type: 'Minion', hero: 'Nuetral', cost: 7, attack: 7, defense: 7, description: ''},
  {name: 'Wild Pyromancer', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 3, defense: 2, description: 'After you cast a spell, deal 1 damage to ALL minions.'},
  {name: 'Windfury Harpy', card_type: 'Minion', hero: 'Nuetral', cost: 6, attack: 4, defense: 5, description: 'Windfury'},
  {name: 'Wisp', card_type: 'Minion', hero: 'Nuetral', cost: 0, attack: 1, defense: 1, description: ''},
  {name: 'Wolfrider', card_type: 'Minion', hero: 'Nuetral', cost: 3, attack: 3, defense: 1, description: 'Charge'},
  {name: 'Worgen Infiltrator', card_type: 'Minion', hero: 'Nuetral', cost: 1, attack: 2, defense: 1, description: 'Stealth'},
  {name: 'Young Dragonhawk', card_type: 'Minion', hero: 'Nuetral', cost: 1, attack: 1, defense: 1, description: 'Windfury'},
  {name: 'Young Priestess', card_type: 'Minion', hero: 'Nuetral', cost: 1, attack: 2, defense: 1, description: 'At the end of your turn, give another random friendly minion +1 Health.'},
  {name: 'Youthful Brewmaster', card_type: 'Minion', hero: 'Nuetral', cost: 2, attack: 3, defense: 2, description: 'Battlecry: Return a friendly minion from the battlefield to your hand.'},
  {name: 'Ysera', card_type: 'Minion', hero: 'Nuetral', cost: 9, attack: 4, defense: 12, description: 'At the end of your turn, draw a Dream Card.'}
]

nuetral_cards.each do |card|
  card = Card.create(card)
end